# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ballan Beauty
email: juicemaster47@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Small AirBnB located near the heart of ballan
sitedescription: >- # this means to ignore newlines until "baseurl:"
  In the heart of Ballan town, by the Werribee River. 45 minutes from Melbourne and 20 minutes from Daylesford, 15-minute walk from Ballan train station! Nestled close to the Werribee River (1 minute walk) & just a 3 minute walk into town.
  Close to Daylesford, Blackwood, Trentham, Ballarat, and Bacchus Marsh.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.ballanbeauty.com/"
logo: assets/img/VerandaView.jpg

# Build settings
markdown: kramdown
#theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
